In [1]:
import numpy as np

In [2]:
a = [1, 2, 5]
print(type(a))

<class 'list'>


In [3]:
arr = np.array(a)
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(arr.shape)

(3,)


In [13]:
a = np.full((3,3),9)
print(a)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [10]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
a = np.random.randint(1, 20, (4, 4))
print(a)

[[17 10  2  1]
 [ 4  4 16 13]
 [15 10 10  3]
 [ 2  9 13  5]]


In [12]:
print(a[1:3 , :])

[[ 4  4 16 13]
 [15 10 10  3]]


In [17]:
import matplotlib

In [18]:
from matplotlib import pyplot as pyplot

In [21]:
x = np.arange(0, 4, 0.1)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9]


In [ ]:
y = np.exp(x)
print(y)
plt.plot(x, y)
plt.show()